### PR TITLE
Reverted breaking changes, and removed console.log.

### PR DESCRIPTION
**Pull request by ghost**
Not sure what your last commit was about, as you broke your code, and added a cosole.log...

This PR reverts those changes to get the code back to being stable. If there is an additional "bug" that you fixed, merge this in and let me know and I will fix it.

### CODE REVIEW

**Comment by hazzo** [comment]
Hi @natezerk, thanks for taking your time to try to fix the code. 

The console log is an error yes, not a huge one...
But revert you have done implies jQuery must be a dependency. As you might know `.remove()` it's a jQuery function. So the changes in the last commit removes that dependency and uses vanilla JavaScript.

I don't know why the code does not work for you. I tested and it was working fine. I will test it again and try te get to the bottom of it.

Thanks again. Have a nice weekend.

**Comment by ghost** [comment]
Thanks @hazzo. 

You unncessarily had the timeout inside the mouseup event listener. Also, no need to remove the ripple element when the ripple container is removed. Please have a test then merge this PR in and release a new version once you're happy.

Thanks a lot mate and happy to help :)

Cheers,
N

**Comment by hazzo** [comment]
Hi @natezerk, thanks again for contributing. 
We were cleaning the code because we got an issue about the console log before your PRs.

I'm sorry but there are some issues with your PR regarding timeouts. The ripple does not clear as smooth as we would like.
By the other side you are right that it's not necessary to remove the ripple because removing the container gets the work done.

Thanks again.

PygmyTeam.

**Comment by ghost** [comment]
@hazzo, there was no issue with the ripple clearing because it just removes it from the DOM, the exact same as what you had before?

Looking at your commits, you still have the same problem... The removal timeout belongs outside of the mouseup event listener...

Poor effort not just merging this in, and letting it be fixed.

**Comment by hazzo** [comment]
Hi @natezerk, why the timeout should be outside of the event listener? If you want to achieve an effect that the ripple clears on mouse up (material guidelines), you must have a clearing method inside the listener, right?

The other issue with the time out were the seconds: `650ms` was not enough to make a smooth clear.

The matter with not merging the pull request is based on not understanding the reason for modifying the code. So if you want to explain it a little bit more we are glad to have another point of view.

**Comment by ghost** [comment]
For starters the point of the code in question (that you wrote...) is to remove the div created by the ripple. Essentially a cleanup that happens after the ripple animation is completed. It has nothing to do with the animation itself.

This PR occurred because your version had a console.log AND the removal was happening too many times causing many JavaScript errors.

Your logic is wrong in the removal of this. I fixed that and that is why I made this PR. Please do not waste other developers time by not taking the time to a) test pull requests and b) merge them in. Instead you have taken bits of this and then introduced wrong logic again (checking if parent exists before removing... you only have to do that because your removal logic is wrong and is firing multiple times...)

Please be aware of these points for future reference.

**Comment by hazzo** [comment]
Please test your code again.

I Just tested (again) and with your changes if you click and hold (in the demo) over the column containing the text `Yes ripple 1`  the ripple disappears. And that's not how it should work because material guidelines state that if you click and hold, the ripple must stay until click is released (issue #4) (Example in the demo of our repo clicking the same column).

We are having a friendly talk and discussing about coding.  But when things of your code were right we took them and thank for it:
> By the other side **you are right** that it's not necessary to remove the ripple because removing the container gets the work done.

So if you think you are wasting time you are wrong. Here we are all contributing to the community and time is not being wasted. But if the whole PR breaks the purpose of our directive as we thought it, we won't approve it. If I have done bad codding and some things are repeated, my bad. We all learn in this life about our errors everyday. 

Nonetheless the directive it is working as we planned.

**Pull request closed without merging**
